--@Autor: Jorge Francisco Pereda Ceballos / Edgar Cristobal Garcia Gutierrez
--@Fecha creación: 16/junio/2023
--@Descripción: Creación de tablas para Sitio 2.

-- drop table STATUS_PROGRAMA; 
-- drop table TIPO_SERIE_R_JPC_S2;
-- drop table ARCHIVO_PROGRAMA_F1_JPC_S2;
-- drop table PLAYLIST_F2_JPC_S2;
-- drop table USUARIO_F2_JPC_S2;
-- drop table TIPO_CUENTA_R_JPC_S2;
-- drop table PAIS_R_JPC_S2;



-- 
-- TABLE: PAIS_R_JPC_S2 
--

CREATE TABLE PAIS_R_JPC_S2(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT pais_pk PRIMARY KEY (PAIS_ID)
)
;


-- 
-- TABLE: TIPO_CUENTA_R_JPC_S2 
--

CREATE TABLE TIPO_CUENTA_R_JPC_S2(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT tipo_cuenta_pk PRIMARY KEY (TIPO_CUENTA_ID)
)
;

-- 
-- TABLE: USUARIO_F2_JPC_S2 
--

CREATE TABLE USUARIO_F2_JPC_S2(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE             NOT NULL,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT usuario_pk PRIMARY KEY (USUARIO_ID),
    CONSTRAINT TIPO_CUENTA_R_JPC_S2_TIPO_CUENTA_ID_FK FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_R_JPC_S2(TIPO_CUENTA_ID)
)
;


-- 
-- TABLE: PLAYLIST_F2_JPC_S2 
--

CREATE TABLE PLAYLIST_F2_JPC_S2(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION          NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT playlist_pk PRIMARY KEY (PLAYLIST_ID),
    CONSTRAINT USUARIO_F2_JPC_S2_USUARIO_ID FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO_F2_JPC_S2(USUARIO_ID)
)
;

-- 
-- TABLE: ARCHIVO_PROGRAMA_F1_JPC_S2 
--

CREATE TABLE ARCHIVO_PROGRAMA_F1_JPC_S2(
    NUM_ARCHIVO    NUMBER(5, 0)     NOT NULL,
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL,
    TAMANO         NUMBER(10, 2)    NOT NULL,
    CONSTRAINT archivo_programa_pk PRIMARY KEY (NUM_ARCHIVO, PROGRAMA_ID)
)
;


CREATE TABLE STATUS_PROGRAMA(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    CONSTRAINT status_programa_pk PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;


-- 
-- TABLE: TIPO_SERIE_R_JPC_S2 
--

CREATE TABLE TIPO_SERIE_R_JPC_S2(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT tipo_serie_pk PRIMARY KEY (TIPO_SERIE_ID)
)
;





