--@Autor: Jorge Francisco Pereda Ceballos / Edgar Cristobal Garcia Gutierrez
--@Fecha creación: 16/junio/2023
--@Descripción: Creación de tablas para Sitio 1.

-- drop table PLAYLIST_F1_JPC_S1;
-- drop table USUARIO_F1_JPC_S1;
-- drop table TIPO_CUENTA_R_JPC_S1;
-- drop table SERIE_F1_JPC_S1;
-- drop table TIPO_SERIE_R_JPC_S1;
-- drop table PELICULA_F1_JPC_S1;
-- drop table DOCUMENTAL_F1_JPC_S1;
-- drop table PAIS_R_JPC_S1;
-- drop table PROGRAMA_F1_JPC_S1;
-- drop table STATUS_PROGRAMA; 

CREATE TABLE STATUS_PROGRAMA(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    CONSTRAINT status_programa_pk PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;
-- 
-- TABLE: PROGRAMA_F1_JPC_S1 
--

CREATE TABLE PROGRAMA_F1_JPC_S1(
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    FOLIO                 VARCHAR2(13)     NOT NULL,
    NOMBRE                VARCHAR2(100)    NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    FECHA_STATUS          DATE             NOT NULL,
    TIPO                  CHAR(1)          NOT NULL,
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT programa_pk PRIMARY KEY (PROGRAMA_ID),
    CONSTRAINT STATUS_PROGRAMA_STATUS_PROGRAMA_ID_FK FOREIGN KEY (STATUS_PROGRAMA_ID)
    REFERENCES STATUS_PROGRAMA(STATUS_PROGRAMA_ID)
)
;

CREATE TABLE PAIS_R_JPC_S1(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT pais_pk PRIMARY KEY (PAIS_ID)
)
;

-- 
-- TABLE: DOCUMENTAL_F1_JPC_S1 
--

CREATE TABLE DOCUMENTAL_F1_JPC_S1(
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    TEMATICA       VARCHAR2(100)    NOT NULL,
    DURACION       NUMBER(5, 2)     NOT NULL,
    PAIS_ID        NUMBER(2, 0)     NOT NULL,
    TRAILER        BLOB             NOT NULL,
    CONSTRAINT documental_pk PRIMARY KEY (PROGRAMA_ID),
    CONSTRAINT DOCUMENTAL_F1_JPC_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JPC_S1(PROGRAMA_ID),
    CONSTRAINT PAIS_R_JPC_S1_PAIS_ID_PK FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS_R_JPC_S1(PAIS_ID)
)
;



CREATE TABLE PELICULA_F1_JPC_S1(
    PROGRAMA_ID      NUMBER(10, 0)    NOT NULL,
    DURACION         NUMBER(5, 2)     NOT NULL,
    SINOPSIS         VARCHAR2(500)    NOT NULL,
    CLASIFICACION    CHAR(1)          NOT NULL,
    PELICULA_ANTECEDENTE_ID NUMBER(10,0) NULL,
    CONSTRAINT pelicula_pk PRIMARY KEY (PROGRAMA_ID),
    CONSTRAINT PELICULA_F1_JPC_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JPC_S1(PROGRAMA_ID)
)
;


-- 
-- TABLE: "TIPO_SERIE_R_JPC_S1" 
--

CREATE TABLE TIPO_SERIE_R_JPC_S1(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT tipo_serie_pk PRIMARY KEY (TIPO_SERIE_ID)
)
;


-- 
-- TABLE: SERIE_F1_JPC_S1 
--

CREATE TABLE SERIE_F1_JPC_S1(
    PROGRAMA_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CAPITULOS        NUMBER(3, 0)     NOT NULL,
    DURACION_CAPITULO    NUMBER(5, 2)     NOT NULL,
    TIPO_SERIE_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT serie_pk PRIMARY KEY (PROGRAMA_ID),
    CONSTRAINT SERIE_F1_JPC_S1_PROGRAMA_ID_FK FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F1_JPC_S1(PROGRAMA_ID),
    CONSTRAINT TIPO_SERIE_R_JPC_S1 FOREIGN KEY (TIPO_SERIE_ID)
    REFERENCES TIPO_SERIE_R_JPC_S1(TIPO_SERIE_ID)
)
;


-- 
-- TABLE: TIPO_CUENTA_R_JPC_S1 
--

CREATE TABLE TIPO_CUENTA_R_JPC_S1(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT tipo_cuenta_pk PRIMARY KEY (TIPO_CUENTA_ID)
)
;


-- 
-- TABLE: USUARIO_F1_JPC_S1 
--

CREATE TABLE USUARIO_F1_JPC_S1(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE             NOT NULL,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT usuario_pk PRIMARY KEY (USUARIO_ID),
    CONSTRAINT TIPO_CUENTA_R_JPC_S1_TIPO_CUENTA_ID_FK FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_R_JPC_S1(TIPO_CUENTA_ID)
)
;

-- 
-- TABLE: PLAYLIST_F1_JPC_S1 
--

CREATE TABLE PLAYLIST_F1_JPC_S1(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION          NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT playlist_pk PRIMARY KEY (PLAYLIST_ID),
    CONSTRAINT USUARIO_F1_JPC_S1_USUARIO_ID_FK  FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO_F1_JPC_S1(USUARIO_ID)
)
;




